apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-deployment
  labels:
    app: location
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location
  template:
    metadata:
      labels:
        app: location
    spec:
      containers:
      - name: location
        image: gcr.io/{{PROJECT_ID}}/location:{{VERSION_TAG}}
        ports:
        - containerPort: 8011
        env:
          - name: GUNICORN_CMD_ARGS
            value: "--bind=0.0.0.0:8011 --workers=2"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/secrets/service-key.json"
          - name: VERSION_TAG
            value: "{{VERSION_TAG}}"
        volumeMounts:
          - name: secrets
            mountPath: /secrets
            readOnly: true
      # [START volumes]
      volumes:
        - name: secrets
          secret:
            secretName: google-account-credentials
      # [END volumes]
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
spec:
  type: ClusterIP
  ports:
  - port: 8011
    targetPort: 8011
  selector:
    app: location
